# Jekyll configuration for mimitfuelpy documentation
title: mimitfuelpy
description: Python library for accessing Mimit Fuel Prices API
url: https://fpetranzan.github.io
baseurl: /mimitFuelPy

# Theme
remote_theme: just-the-docs/just-the-docs@v0.8.2

# Color scheme
color_scheme: light

# Enable search
search_enabled: true
search:
  heading_level: 2
  previews: 2
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Heading anchor links appear on hover over h1-h6 tags in page content
heading_anchors: true

# External navigation links
nav_external_links:
  - title: GitHub Repository
    url: https://github.com/fpetranzan/mimitFuelPy
    hide_icon: false
  - title: PyPI Package
    url: https://pypi.org/project/mimitfuelpy/
    hide_icon: false

# Footer content
footer_content: "Copyright &copy; 2025 Francesco Petranzan. Distributed under the <a href=\"https://github.com/fpetranzan/mimitFuelPy/blob/master/LICENSE\">MIT License</a>."

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer last edit timestamp
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

# GitHub edit link
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/fpetranzan/mimitFuelPy"
gh_edit_branch: "master"
gh_edit_source: ""
gh_edit_view_mode: "tree"

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - node_modules/
  - "*.gemspec"
  - "*.gem"
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - script/
  - LICENSE.txt
  - lib/
  - bin/
  - README.md
  - Rakefile
  - docs/tests/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - src/
  - tests/
  - examples/
  - setup.py
  - pyproject.toml
  - MANIFEST.in
  - Makefile
  - CHANGELOG.md

# Kramdown options
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Compression
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false